services:
  - type: web
    name: Banandivps
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: STORAGE_DIR
        value: /opt/render/project/src/storage
    autoDeploy: true
